### ISSUE TITLE
Error when trying to delete post

### ISSUE THREAD

**Issue by hendrikcech** [Campr/Bugs#1]
I'm getting an error when trying to delete a post:
401 Unauthorized: Exception of type 'TentServ.Lib.Exceptions.CustomHttpException' was thrown.  
Look for post `47f792f2143d4f5694a7db262865b25f` by `trtest.campr.me` in your logs. The last time I tried deleting it was 5:01am UTC.  
Since I'm trying to delete a post that was just created a moment before with the same authentication, the error message must be wrong.

**Comment by quentez** [comment]
Do you think you could give me the full HTTP request you made to get this result?
I'm thinking it might be a routing issue.

I probably should have this in my logs... But my logging strategy is yet to be fully featured :S

**Comment by hendrikcech** [comment]
Of course, I should have included that in the first place.
As I look at the request right now, I'm wondering if I should set a content-type header..

**Request:**
DELETE https://campr.me/trtest/posts/https://trtest.campr.me/47f792f2143d4f5694a7db262865b25f
host: campr.me
authorization: Hawk id="7fcebacc9fc94b5abce7b5950da8ccbe", ts="1396690550", nonce="IfQ4iA", mac="/a9MHQC0q/g2LxwyOK2vvbhP/bSJZUvwnHMxS6ZFy1I="

**Response:**
401 Unauthorized
cache-control: no-cache
pragma: no-cache
content-type: application/vnd.tent.error.v0+json
expires: -1
server: Microsoft-IIS/8.0
x-aspnet-version: 4.0.30319
x-powered-by: ASP.NET
date: Sat, 05 Apr 2014 09:35:52 GMT
content-length: 87

{ error: 'Exception of type \'TentServ.Lib.Exceptions.CustomHttpException\' was thrown.' }

**Comment by quentez** [comment]
Tent requires entities to be URL encoded when used in a request's path or query string. Cupcake might tolerate non URL encoded entities, but Campr doesn't.
