### ISSUE TITLE
Campr Invite

### ISSUE THREAD

**Issue by Adam24** [Campr/Bugs#4]
Quentin, Can you spare an invite to campr?

**Comment by quentez** [comment]
Hey there Adam. I was traveling last week and didn't see this issue until today. I'll send an invite tomorrow ;) !

**Comment by Adam24** [comment]
ok!

On Sun, Jan 11, 2015 at 5:40 PM, Quentin Calvez notifications@github.com
wrote:

> Hey there Adam. I was traveling last week and didn't see this notification
> until today. I'll send an invite tomorrow ;) !
> 
> —
> Reply to this email directly or view it on GitHub
> https://github.com/Campr/Bugs/issues/4#issuecomment-69517891.

## 

--Adam Robertson-- (write back)
